# Generated by Django 3.2.7 on 2021-09-24 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productManager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('Product_id', models.IntegerField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=100)),
                ('product_image', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'products',
            },
        ),
    ]
