# Generated by Django 3.2.7 on 2021-09-25 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productManager', '0003_auto_20210925_0116'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='productmovements',
            table='product_movements',
        ),
    ]
