# Generated by Django 3.2.7 on 2021-09-25 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productManager', '0004_alter_productmovements_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='puser',
            table='users',
        ),
    ]
