# Generated by Django 3.2.7 on 2021-09-25 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productManager', '0005_alter_puser_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productManager.product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='added_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productManager.puser'),
        ),
        migrations.AlterField(
            model_name='productmovements',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productManager.product'),
        ),
    ]
