# Generated by Django 3.2.7 on 2021-09-25 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productManager', '0006_auto_20210925_1149'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productmovements',
            old_name='product_id',
            new_name='product_ed',
        ),
    ]
