# Generated by Django 3.2.7 on 2021-09-25 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productManager', '0007_rename_product_id_productmovements_product_ed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmovements',
            name='product_ed',
        ),
        migrations.AddField(
            model_name='productmovements',
            name='product_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='movelocation', to='productManager.product'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='location',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location', to='productManager.product'),
        ),
    ]
