# Generated by Django 3.2.7 on 2021-09-25 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productManager', '0010_auto_20210925_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Product_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='puser',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
