# Generated by Django 3.2.7 on 2021-09-25 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productManager', '0011_auto_20210925_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='location_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
