# Generated by Django 3.2.7 on 2021-09-25 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productManager', '0013_alter_productmovements_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='location_id',
            field=models.IntegerField(blank=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productmovements',
            name='id',
            field=models.IntegerField(blank=True, primary_key=True, serialize=False),
        ),
    ]
