# Generated by Django 3.2.7 on 2021-09-25 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productManager', '0016_alter_productmovements_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='location_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='Product_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='puser',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
