# Generated by Django 3.2.7 on 2021-09-28 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productManager', '0017_auto_20210925_1620'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='added_by',
        ),
    ]
