# Generated by Django 3.2.7 on 2021-09-28 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productManager', '0018_remove_product_added_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='added_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='productManager.puser'),
            preserve_default=False,
        ),
    ]
